import type { ThemeConfig } from 'antd'

export const circlesTheme: ThemeConfig = {
  token: {
    fontSize: 14,
    fontSizeSM: 12,
    fontSizeLG: 16,
    fontSizeXL: 20,
    fontSizeHeading1: 38,
    fontSizeHeading2: 30,
    fontSizeHeading3: 24,
    fontSizeHeading4: 20,
    fontSizeHeading5: 16,
    lineHeight: 22 / 14,
    lineHeightHeading1: 46 / 38,
    lineHeightHeading2: 38 / 30,
    lineHeightHeading3: 32 / 24,
    lineHeightHeading4: 28 / 20,
    lineHeightHeading5: 24 / 16,
    fontWeightStrong: 600,
    colorPrimary: '#1677ff',
    colorSuccess: '#52c41a',
    colorWarning: '#faad14',
    colorError: '#cf1322',
    colorText: '#1f1f1f',
    colorTextHeading: '#1f1f1f',
    colorTextSecondary: '#595959',
    colorTextDescription: '#8c8c8c',
    colorTextDisabled: '#bfbfbf',
    colorIcon: 'rgba(0, 0, 0, 0.45)',
    colorSplit: 'rgba(5, 5, 5, 0.06)',
    colorFillAlter: 'rgba(0, 0, 0, 0.02)',
    colorFillSecondary: 'rgba(0, 0, 0, 0.06)',
    colorFillTertiary: 'rgba(0, 0, 0, 0.04)',
    colorBgContainerDisabled: 'rgba(0, 0, 0, 0.04)',
    colorBorder: '#d9d9d9',
    colorBorderSecondary: '#f0f0f0',
    colorBgLayout: '#fbfbfb',
    borderRadius: 6,
    borderRadiusLG: 8,
    padding: 16,
    paddingLG: 24,
  },
  components: {
    Card: {
      paddingLG: 24,
      headerBg: '#ffffff',
      colorBorderSecondary: '#f0f0f0',
      // Header tint of type="inner" cards; half the global colorFillAlter.
      colorFillAlter: 'rgba(0, 0, 0, 0.01)',
    },
    Collapse: {
      headerBg: 'rgba(0, 0, 0, 0.01)',
    },
    Table: {
      headerBg: '#fafafa',
      footerBg: '#ffffff',
      footerColor: '#1f1f1f',
      borderColor: '#f0f0f0',
      headerSplitColor: '#f0f0f0',
      rowHoverBg: '#fafafa',
      headerSortActiveBg: '#fafafa',
      headerSortHoverBg: '#fafafa',
      fixedHeaderSortActiveBg: '#fafafa',
      bodySortBg: 'transparent',
    },
    Input: {
      activeBg: '#ffffff',
      hoverBg: '#ffffff',
      activeBorderColor: '#1677ff',
      hoverBorderColor: '#4096ff',
      activeShadow: '0 0 0 2px rgba(5, 145, 255, 0.1)',
      addonBg: 'rgba(0, 0, 0, 0.02)',
    },
    Menu: {
      itemHoverBg: 'rgba(0, 0, 0, 0.04)',
      itemHoverColor: '#1f1f1f',
    },
    Divider: { colorSplit: 'rgba(5, 5, 5, 0.06)' },
    Pagination: {
      itemBg: '#ffffff',
      itemActiveBg: '#ffffff',
      itemInputBg: '#ffffff',
      itemLinkBg: '#ffffff',
    },
    Segmented: {
      trackBg: '#ffffff',
      itemHoverBg: '#fafafa',
      itemSelectedBg: '#fafafa',
      itemActiveBg: '#fafafa',
    },
  },
}
